# 异常处理

## 处理机制
高级语言通常都内置了一套try...except...finally...的错误处理机制，Python也不例外 
 * 文档 https://docs.python.org/zh-cn/3.8/tutorial/errors.html

```
try:
    print('try...')
    r = 10 / 0
    print('result:', r)
except ZeroDivisionError as e:
    print('except:', e)
finally:
    print('finally...')
print('END')
```
* Python的错误其实也是class，所有的错误类型都继承自BaseException，所以在使用except时需要注意的是，它不但捕获该类型的错误，还把其子类也“一网打尽”。比如：
```
try:
    foo()
except ValueError as e:
    print('ValueError')
except UnicodeError as e:
    print('UnicodeError')

```
* 第二个except永远也捕获不到UnicodeError，因为UnicodeError是ValueError的子类，如果有，也被第一个except给捕获了。
* 异常的继承关系 :https://docs.python.org/3/library/exceptions.html#exception-hierarchy . 
* 中文 内置异常 https://docs.python.org/zh-cn/3.8/library/exceptions.html#bltin-exceptions
* 出错要记得打印,异常栈


## 记录错误

*  Python内置的logging模块可以非常容易地记录错误信息
```
# err_logging.py

import logging

def foo(s):
    return 10 / int(s)

def bar(s):
    return foo(s) * 2

def main():
    try:
        bar('0')
    except Exception as e:
        logging.exception(e)
        
main()
print('END')
``` 
 logging模块还可以打印日志到文件,可以查查文档学习  https://docs.python.org/zh-cn/3.8/library/logging.html
 
 ## 抛出错误
 
 * 自定义异常类,在检测到异常的时候, 我们通常要记录日志, 同时要把异常继续通过raise抛出,顶层调用者会处理
 
```
class MyError(ValueError):
    pass

def f(s):
    n = int(s)
    if n == 0:
        raise MyError('invalid value : %s' %s)
    return 10 / n

def bar():
    try:
        f('0')
    except ValueError as e:
        print('ValueError',e)
        raise 
# raise 不带参数就是把原来异常 继续抛出, raise也可以转换另一种异常抛出
bar()
```
